version: "3.1"

services:
  nginx:
    image: nginx:1.20.0
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - api

  app:
    image: guillaudev/localize_api:latest
    container_name: localize-app
    restart: unless-stopped
    working_dir: "{{ back_end_workdir }}"
    volumes:
      - ./:/var/www/
      - ./upload/:/var/www/public/upload/
    networks:
      - api

networks:
  api:
    driver: bridge