---

- name: Install Docker
  hosts: localhost
  become: yes
  roles:
    - { role: geerlingguy.docker, tags: ["docker"] }
    - { role: geerlingguy.pip, tags: ["pip"] }

- name: Deploy inside code
  import_playbook: back_end.yml
  tags: ['back_end']